# .travis.yml for ices-tools packages

# Header
os: linux
dist: xenial
language: r
cache: packages
warnings_are_errors: false

# notifications
notifications:
  email:
    on_success: change
    on_failure: change

repos:
  CRAN: https://cloud.r-project.org

# r_packages
r_packages:
  - testthat
  - rmarkdown
  - covr
  - XML

# after_success
after_success:
  - Rscript -e 'covr::codecov()'
