# .travis.yml for ices-tools packages

warnings_are_errors: false

matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: beta-xcode6.1

language: r
r:
  - release

sudo: false

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - rmarkdown

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'

